import{repository}from'./src/db.js';import{createMeeting}from'./src/models.js';import{RecorderController}from'./src/recorder.js';import{BrowserTranscriptionProvider}from'./src/transcription.js';import{renameSpeaker}from'./src/speakers.js';import{LocalMeetingIntelligence}from'./src/ai.js';import{downloadMeetingTxt,shareMeeting}from'./src/export.js';
let mode='standard',active=null,recorder=null,speech=null,timerId=null,waveId=null,detail=null;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));$('#bottom-nav').hidden=['recording-view','meeting-detail-view'].includes(id);if(id==='meetings-view')renderMeetings();if(id==='home-view')renderRecent();if(id==='settings-view')renderCapabilities()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>showView(b.dataset.back));
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));$('#privacy-pill').textContent=mode==='privacy'?'Privacy 🔒':'Standard'});
async function renderRecent(){if(!repository)return;try{const ms=(await repository.listMeetings()).slice(0,3);$('#recent-list').innerHTML=ms.length?ms.map(card).join(''):'<div class="card"><p class="meta">No meetings yet. Your recordings stay on this device.</p></div>';bindCards()}catch(e){toast('Storage unavailable: '+e.message)}}
function card(m){return`<div class="card"><button data-meeting="${m.id}"><b>${esc(m.title)}</b><p class="meta">${new Date(m.createdAt).toLocaleString()} · ${m.mode==='privacy'?'🔒 Privacy':'Standard'}</p></button></div>`}
function bindCards(){document.querySelectorAll('[data-meeting]').forEach(b=>b.onclick=()=>openMeeting(b.dataset.meeting))}
async function renderMeetings(q=$('#meeting-search')?.value||''){if(!repository)return;try{const ms=await repository.searchMeetings(q);$('#meeting-list').innerHTML=ms.length?ms.map(card).join(''):'<div class="card"><p class="meta">No matching meetings.</p></div>';bindCards()}catch(e){toast('Storage error: '+e.message)}}
$('#meeting-search').oninput=e=>renderMeetings(e.target.value);
$('#start-meeting').onclick=async()=>{active=createMeeting({title:'Meeting '+new Date().toLocaleDateString(),mode});$('#record-mode').textContent=mode==='privacy'?'PRIVACY MODE · LOCAL FIRST':'STANDARD MODE';$('#record-title').textContent=active.title;$('#live-transcript').innerHTML='';showView('recording-view');try{recorder=new RecorderController();await recorder.start();$('#recording-status').textContent='Recording in foreground. Keep MEETRA open for reliable capture.';startTimer();startWave();startSpeech()}catch(e){$('#recording-status').textContent='Recording cannot start: '+e.message;toast('Microphone unavailable. Check Safari permission.')}};
function startTimer(){const started=Date.now();clearInterval(timerId);timerId=setInterval(()=>{const s=Math.floor((Date.now()-started)/1000);$('#timer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`},250)}
function startWave(){const w=$('#wave');w.innerHTML=Array.from({length:36},()=>'<i></i>').join('');waveId=setInterval(()=>w.querySelectorAll('i').forEach(i=>i.style.height=(8+Math.random()*48)+'px'),140)}
function startSpeech(){if(mode==='privacy'){$('#live-transcript').innerHTML='<p class="meta">Live transcription disabled in Privacy Mode to avoid browser speech services that may use network processing. Audio recording continues locally.</p>';return}speech=new BrowserTranscriptionProvider();if(!speech.isSupported()){$('#live-transcript').innerHTML='<p class="meta">Live speech recognition is not supported by this browser. Audio recording can continue; no transcript will be fabricated.</p>';return}try{speech.start(seg=>{seg.timestampMs=Date.now();active.transcriptSegments.push(seg);renderLive()},err=>toast('Speech recognition stopped: '+err))}catch(e){toast(e.message)}}
function renderLive(){$('#live-transcript').innerHTML=active.transcriptSegments.map(s=>`<div class="segment"><b>${esc(s.speakerName)}</b><br>${esc(s.text)}</div>`).join('')}
$('#pause-record').onclick=()=>{if(!recorder)return;if(recorder.state==='recording'){recorder.pause();$('#pause-record span').textContent='Resume';$('#recording-status').textContent='Paused'}else{recorder.resume();$('#pause-record span').textContent='Pause';$('#recording-status').textContent='Recording in foreground'}};
$('#highlight-record').onclick=()=>{if(active){active.markers.push(Date.now());toast('Moment marked')}};
$('#end-record').onclick=async()=>{if(!recorder||!active)return;try{const out=await recorder.stop();speech?.stop();clearInterval(timerId);clearInterval(waveId);active.audioBlob=out.blob;active.durationMs=out.durationMs;active.aiResult=new LocalMeetingIntelligence().generate(active.transcriptSegments);await repository.saveMeeting(active);await openMeeting(active.id);toast('Meeting saved locally')}catch(e){toast('Save failed — meeting was not reported as saved: '+e.message)}};
async function openMeeting(id){try{detail=await repository.getMeeting(id);if(!detail)return;$('#detail-title').textContent=detail.title;renderDetail();showView('meeting-detail-view')}catch(e){toast('Storage error: '+e.message)}}
function renderDetail(){const a=detail.aiResult||new LocalMeetingIntelligence().generate(detail.transcriptSegments);const items=(x,f=x=>x)=>x?.length?x.map(v=>`<li>${esc(f(v))}</li>`).join(''):'<li class="meta">None identified</li>';$('#detail-content').innerHTML=`<div class="card"><p class="meta">${new Date(detail.createdAt).toLocaleString()} · ${detail.mode==='privacy'?'🔒 Privacy Mode':'Standard Mode'} · ${Math.round((detail.durationMs||0)/1000)} sec</p><button id="share-detail">Share</button> <button id="export-detail">TXT</button></div><div class="card"><small>LOCAL MEETING INTELLIGENCE</small><h3>Summary</h3><p>${esc(a.summary)}</p><h3>Key Decisions</h3><ul>${items(a.decisions)}</ul><h3>Action Items</h3><ul>${items(a.actionItems,x=>x.text)}</ul><h3>Unresolved Topics</h3><ul>${items(a.unresolvedTopics)}</ul></div><div class="card"><h3>Transcript</h3>${detail.transcriptSegments.length?detail.transcriptSegments.map(s=>`<div class="segment"><button class="speaker-name" data-speaker="${s.speakerId}"><b>${esc(s.speakerName)}</b></button><br>${esc(s.text)}</div>`).join(''):'<p class="meta">No transcript available. This browser did not provide live speech recognition.</p>'}</div>`;$('#share-detail').onclick=()=>shareMeeting(detail);$('#export-detail').onclick=()=>downloadMeetingTxt(detail);document.querySelectorAll('.speaker-name').forEach(b=>b.onclick=async()=>{const name=prompt('Speaker name',b.textContent.trim());if(name){detail.transcriptSegments=renameSpeaker(detail.transcriptSegments,b.dataset.speaker,name);await repository.saveMeeting(detail);renderDetail()}})}
function renderCapabilities(){const rows=[['Microphone / MediaRecorder',!!navigator.mediaDevices?.getUserMedia&&!!globalThis.MediaRecorder],['Live Speech Recognition',!!(globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition)],['Local IndexedDB Storage',!!globalThis.indexedDB],['Web Share',!!navigator.share]];$('#capability-list').innerHTML=rows.map(([n,ok])=>`<div class="card"><b>${n}</b><p class="meta">${ok?'Available':'Not available in this browser'}</p></div>`).join('')}
$('#delete-data').onclick=async()=>{if(confirm('Delete all locally stored MEETRA meetings on this device?')){try{await repository.clear();toast('Local meeting data deleted');renderRecent()}catch(e){toast('Storage error: '+e.message)}}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');renderRecent();
